apiVersion: v1
data:
  ENV_VAR_1: fake
  ENV_VAR_2: more-faker
kind: ConfigMap
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-config
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    app: example
    component: nginx
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx
spec:
  ports:
  - port: 80
  selector:
    app: example
    component: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    app: example
    component: nginx
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx
spec:
  selector:
    matchLabels:
      app: example
      component: nginx
  template:
    metadata:
      annotations:
        kots.io/app-slug: craigkotstest
      labels:
        app: example
        component: nginx
        kots.io/app-slug: craigkotstest
        kots.io/backup: velero
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: example-config
        image: nginx
        name: nginx
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 32Mi
      imagePullSecrets:
      - name: craigkotstest-registry
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: craigkotstest-registry
  namespace: cbodonnell
spec:
  encryptedData:
    .dockerconfigjson: AIA32esbW8xh8Zdn9j6u1qbs91W/LrsAksTyHPVSEgdz7fPvAPFpzsqLHmBrzTY1tSqETVcFkTWEnTCCQvuPUDCehqEWlGl88MjPKKG2vg+v4ujpYgf2zEBALR/XXLAAuIz5V6ZuwaE51wNsQdUlW/3DjxEjAcAlQ+onKA7MNCMcBPt0+JhIZyNtG4PzhPHlwRVru4XNHyDTizkExlbJ4quxQxFppDXtznAesKSZxPTzp4yoS10hDho9jSFIDwzjJg3yoU4gf3xyf7+woDmmiohpu1ZO+M/kI076X6e+ru2lCkbcQA/v0eQZiVNF2275a0GSb1yqGx54mgR0zcQ5NCWGP0IIpOwEN0u3FVcglBHdVqiCTmnTnM55qdJo8WZtPKM9Y7elIeukXE579TP2LPBBEkwKrm/UpUqe8J30bJ9yvIAFTIQCNmBxyctiI5tV33tKC5Jhfnabtfmuy74HUqbByhabhf0a43mJevZL4i8jVcAjvsE6zbX+ogoKWw==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: craigkotstest-registry
      namespace: cbodonnell
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: kotsadm-replicated-registry
  namespace: cbodonnell
spec:
  encryptedData:
    .dockerconfigjson: AIB7vfNfuQ6NhEpWCNffSMR0OcoOUeQeWOFflnrJWYCdYeF9iB9gP7J3iVrhtl5CAiWwMeauhYSAICorxNTIyG9D9ZZRDDxQdsoeYHt0Suemlk46/eufdjz9arvIBu2xhcSeaIYf1rVOmeOndD/iT53pFxBqpiZo/WLJ3XpMlDS6UzH4TiTbiXLrwRtBHNxm0OOIOKs3vscRtHAudzLh9S9R1PBE04hU1Vboz/OyfOjw3ZBE9SefGOvqzcdQv84ACZF9vfkp2W9ah/DMbjN6YmW0AfWZQKSfo3mOeik/sltqnOvyKR+9MZ+aIcouByMpqVkug3Kte71B09JLetSfz6gnpQr4RX8WzbWwTzciDRvhJj2LUDiMnQIlvJW6ZTbDtQLnK2tHaMMGkCI0SIk/06akoUMZT5ySSR+AcROGrAEKdb0qYZDASaNan4fZQxUkTF1f9FK6j8RY7RKWQQD6Bc5eLDuDKu2q/6YjQ+B2f+7+hJYJY71nTFECFsIHNQ==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: kotsadm-replicated-registry
      namespace: cbodonnell
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: mysecret
  namespace: cbodonnell
spec:
  encryptedData:
    PASSWORD: AIAWC/fQTAUfAqGLJ4HUCaxvtvYu+JqK1hbM9BN6yRcAWeqaLhos2HOlunfznas/vLElKYKi/U1IxbcoghUF43ToxOcrDlQ572t+lEK3maYxd6shaIHHb2BkpVNcaLcBFCkHJiaf4t66vn2KHF35ExqT8O6esN0r0yr3DSg710Op1Cou+TqZwzQisR1LHwxICrL9BP+fbCJdlbFf35s=
    USER_NAME: AIABXHricR5RporEmS7YYSx7lvit/o66+Z1vzDpp/OcC6chJr7sy+QRfPC/c7LC21ts3x3xpHAiiUUhmZCSFHeH8RKV58k8QDmiJOiMVPAzQ3jPCnr3PNw+NMMj6jpqnyYf98zrE4zFl/6NELWQ2ioQyxH7QxYeVjSM5XlyLuza+l4d1vJeQComAHmHwgErZ7DRbSLcZQQ==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: cbodonnell
    type: Opaque
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: example-nginx
            port:
              number: 80
        path: /
        pathType: Prefix
