apiVersion: v1
data:
  ENV_VAR_1: fake
  ENV_VAR_2: more-faker
kind: ConfigMap
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-config
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    app: example
    component: nginx
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx
spec:
  ports:
  - port: 80
  selector:
    app: example
    component: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    app: example
    component: nginx
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx
spec:
  selector:
    matchLabels:
      app: example
      component: nginx
  template:
    metadata:
      annotations:
        kots.io/app-slug: craigkotstest
      labels:
        app: example
        component: nginx
        kots.io/app-slug: craigkotstest
        kots.io/backup: velero
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: example-config
        image: nginx:1.21
        name: nginx
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 32Mi
      imagePullSecrets:
      - name: craigkotstest-registry
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: craigkotstest-registry
  namespace: cbodonnell
spec:
  encryptedData:
    .dockerconfigjson: AICQnie9jrhL29TcCSSkcOXBh7r0p3MJAfNSWLLyo5q7bLanV1rOaXa0Gbk2mkYcc3FMs6vc9BrzgYqp8bYW80WKznecZH7frLqhaI5cLUJjzyq+0xwUf38Jrp55Rp+2VQ5OmTWQhZYBvztapJBqSoaPAUh6tE97mlUBVGqSOfCyI2Pro8vmXb9FlQrrRbRPplPpjcJEap89rWHOel1iaK2+onOHN9JmrXuUnCCPMlTWMS8hcKX1BPlZ2d/qo9FIWlMgpQ0O5dkj3uRlAKMY888+GyZeOHcD7fq+BYw/wEpZbEahB1YdQXvnDJUlHyDi37hTPq97IyKHO04wRyPhIdl5qVqEdqcdVfhI8MahZy+i314ojjJKPaXBdiI20M1n6jR2JHAqmFrREnf/niWoa7IcvogwLVD4HWH1DYfKxaBdJtK1Jd9MRiD9a8st4NiEM3DY6YPYdPw1Pd99Hr7vEKO9nlI6dxlpycdS8AEiKbPSLfkQQp9ZfQzyziMq7Q==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: craigkotstest-registry
      namespace: cbodonnell
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: kotsadm-replicated-registry
  namespace: cbodonnell
spec:
  encryptedData:
    .dockerconfigjson: AIA0ZHwv5LH37h6vhNVtrdSG8pGIlD3rPYDA3zqSHXmn28xie4/QZDoQwFznssHfk5C3MHCfG4Zelbm4C67j+nry24YeMAP5nE68QvvjOkp7Tvl7cFRMa58+pvmbgfS0EkHst+F1srk2ZfamHkwI3VtEgHbKu7VTzGi/DGfDpJVuFsF89Y3gL4PxdkqeBjHYTGYYOjq2JjXY6cYIebz3yqUBe94uj8GG8zso8l4/T65zcY+rvJ3QT9a5NVIuZycyekOaIPYRZEfzxRQXEN/ay1k4rpsphRTPvzu+0NUrCKUxzcA1en4uwDYYctE+h4Ipgkn0WbrA42lUpXQq90GgDwTV7y5zYUhCe2sLusGuZm7XGw3Zz+SmyWcPUCcJtsjr/zCcoVHcdFPltMKvMauNF+kuWNH1Pw0JAZU3bMPN37eBp0Ee1i+mwMVf7+5o33edlVIyUvkEdwIQDs9yfRRZYdRu2qY8+OrxpxM/szV36TFX5fXhXBViyIGoBaghVA==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: kotsadm-replicated-registry
      namespace: cbodonnell
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: mysecret
  namespace: cbodonnell
spec:
  encryptedData:
    PASSWORD: AIBlmbCgJXq8GpqcYdrxVsfPS0cAcxwemf47sUea513IVDJLFmvAS2bEkXyiFRi9n5fJsa5DV//+xfZ00V7HkPC5mW+KLLuIX592VqCUDO4URngVIjPNK/se77zlXEZuVuonmFbkV+SjT6DhNWEbJZIQKZ+zBSN38zTtvs0d+eL1rtcqfFJWrUZ8bkNqdKWjHcgt1WULE2QPCOj07RM=
    USER_NAME: AIArPn8I9S9cscYVrAOPxMLXPQjhBeRyA647FTLaYqs3Ak9rby9lZTgCMT9sHcrKGLHfmSH0VFnjiR2E6uQnM0klyVHB7YC3pciVNhKg3v8ndzugnOvNyYZ3QQT641WVYT+OzcLNCSLy+HYcBwqd7IDkWxRqR3IUSFhrOOcq9WPcbjD7c3e2mBw8DXESRcxfBV6M1dByyg==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: cbodonnell
    type: Opaque
---
apiVersion: cluster.kurl.sh/v1beta1
kind: Installer
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: c71cda8-v2
spec:
  containerd:
    version: 1.5.x
  contour:
    version: 1.21.x
  ekco:
    version: latest
  kotsadm:
    version: latest
  kubernetes:
    version: 1.23.x
  longhorn:
    version: 1.2.x
  minio:
    version: 2020-01-25T02-50-51Z
  prometheus:
    version: 0.56.x
  registry:
    version: 2.7.x
  weave:
    version: 2.6.x
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: example-nginx
            port:
              number: 80
        path: /
        pathType: Prefix
