apiVersion: v1
data:
  ENV_VAR_1: fake
  ENV_VAR_2: more-faker
kind: ConfigMap
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-config
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    app: example
    component: nginx
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx
spec:
  ports:
  - port: 80
  selector:
    app: example
    component: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    app: example
    component: nginx
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx
spec:
  selector:
    matchLabels:
      app: example
      component: nginx
  template:
    metadata:
      annotations:
        kots.io/app-slug: craigkotstest
      labels:
        app: example
        component: nginx
        kots.io/app-slug: craigkotstest
        kots.io/backup: velero
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: example-config
        image: nginx:1.21
        name: nginx
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 32Mi
      imagePullSecrets:
      - name: craigkotstest-registry
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: craigkotstest-registry
  namespace: cbodonnell
spec:
  encryptedData:
    .dockerconfigjson: AICKtReKw6OGos5a1wEcaTS3aDW4BZhmRD+IpQBYNXNNXXB5OJJe2T7OPw7P3G5KbpOgwx46it2f49jkm+Hr5FiMl+olsCMf4ly0H3gxxJlOCdot93bDeShkFuf2vNNMdIfLlS2h+8NZgicSGedVlob11Sb8R4R+jRTS4hffG8lIhPHWB6sEQzO4geXf6LLVxUwI9Ry9Xyte4l2Fo9zH2w05v1bGLlqXxGiKp93vlqlcV5258LERIxEO/gxc5BHokmWBxcY+wbdT6DMbh9A/kyucH5f22YTDbl2Hdr0C+FFeEG6lSaqPoQX6Jj74K9stAoqQ+CroO1aPe2NHXkT++LobPMpc1R7xECHDJjtDs85gnjYP41BTXI6hyxLgnfAYznxAk87kYLiwgeGunOR8f50+M4FAYcKlWSoVrVBioSkIHD7nzhWr2s7OPeBr3Czh2LcbZFhEqgWDNtQ9oLSsmygMiIfJreIl+m0m9MuoefVW+x3rBVTkkwl+z56ysw==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: craigkotstest-registry
      namespace: cbodonnell
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: kotsadm-replicated-registry
  namespace: cbodonnell
spec:
  encryptedData:
    .dockerconfigjson: AICvJL/O7CLUmckIvdIcNzsSX9HkKBNrxiu8Icm7MokvSoWx0NryB5GA05qjQmEc3gsGzYEXd48mT/OtuHhKiULKf6hwBuPEZxi4ESJ0z5k7vhJmtdva82YTtufQ/yMve3qMCkPJfQ4uIqMZYneTA5RPsfbjaOOjfo/dYKF+om7PsbegnjectGrgo2cKNpfrKC+2qGvTzw8+gwqiddJzr9dyOj5L0fR9T/bPAV/NPtnO6EKTBbt895GjnqIXpvOrUCN8FlY9Ib87yyzUMfPLR+HKE06TQv16dA8MAX/xqx36prwkAKFyWrGfmK83J/XaHTDH0W6UYviV+jSEz+KT1ij3abUV6RdpxmC9NDKk/hHW3t+mhNivNXiudpHsE2meigmFrCfnLFKNzRFQxLoMd+Kl5SyePpN+nzhzHSuhr10RJbY5FT8g9bgSsbe3FspKtqpyW+5GQZErhk7MybLVYl4+szVSIEiBtznI28bfQF/8g3HzGMtbeZUEz4+luw==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: kotsadm-replicated-registry
      namespace: cbodonnell
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: mysecret
  namespace: cbodonnell
spec:
  encryptedData:
    PASSWORD: AIAMuQhx42okfTtE+RJTs9bvNHDXxD0cB1FJzDkje5stUN894QfgEuv8RVDomDUNISzsl5hm6BnKvRdb0gxRMfg09z9jop5EDuA6uFAE/RcknlhGqw4mLt6lldksFyfo9qYz7IlIv4+8z/LRLfmj5KmY61NEdxu37ZDn+ddzFDqHj7Cw+3WarvCMsBeQCeMsUwd0uFwLdZ+h0L6ewCo=
    USER_NAME: AIDGpwje45IBjoHu5563aGjDxPw6K0UaZqy/cwuIwAoYnZhG/jUOPK4T0btUK+xEESE5N8pZsL2hMQkgreq7CxZXojvWnS3U/2Fmy1o2+2QMfacmI3AqpyZNBdGxg965+S6HAk0qFagj2/9uWxhqLX2JSVmA1KRk9UubtrVnhfNgY6oIBIH9uYhzr6zQO27q7fcl7aDRtA==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: cbodonnell
    type: Opaque
---
apiVersion: cluster.kurl.sh/v1beta1
kind: Installer
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: c71cda8
spec:
  containerd:
    version: 1.5.x
  contour:
    version: 1.21.x
  ekco:
    version: latest
  kotsadm:
    version: latest
  kubernetes:
    version: 1.23.x
  longhorn:
    version: 1.2.x
  minio:
    version: 2020-01-25T02-50-51Z
  prometheus:
    version: 0.56.x
  registry:
    version: 2.7.x
  weave:
    version: 2.6.x
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: example-nginx
            port:
              number: 80
        path: /
        pathType: Prefix
