apiVersion: v1
data:
  ENV_VAR_1: fake
  ENV_VAR_2: more-faker
kind: ConfigMap
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-config
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    app: example
    component: nginx
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx
spec:
  ports:
  - port: 80
  selector:
    app: example
    component: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    app: example
    component: nginx
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx
spec:
  selector:
    matchLabels:
      app: example
      component: nginx
  template:
    metadata:
      annotations:
        kots.io/app-slug: craigkotstest
      labels:
        app: example
        component: nginx
        kots.io/app-slug: craigkotstest
        kots.io/backup: velero
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: example-config
        image: nginx
        name: nginx
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 32Mi
      imagePullSecrets:
      - name: craigkotstest-registry
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: craigkotstest-registry
  namespace: cbodonnell
spec:
  encryptedData:
    .dockerconfigjson: AICaIZbVoLYotMI15hECvM+Jc+mGErQvRnpoHRjpTGS2yXPn3Xt2hTq1DrUFEBJ0pgg6psKtYDdRQRzYQAGk9z7c92c+huUu+ttKCj4VkdQ3VUp6z1DEjyuIjF5vg8r28/vpkqZhTUWePkPXPWcgic9pUb0MO78EHnlmvccpLFn/XUZNZPQFh3P+AU33mgXfuNcc4chHQu05ZuFmT8+j3Wm4tsnCG1iGbreTV2V5GA/xcW+Dq0ZisN+UoDMnHZcE+U/ikeTTDjEHrIq9u0VD3ObhxrrRS2PAxRmlGmhQDsMmciBoRiHZNtpfhI9T0PVmW1Gi3Iuc+U+aefT9mZbAusBwildJtghCXW0triPVZbARHbFwQeotB5Sr2RIc15OmKem3UTFfeNskh2jp1i45rFFHQa6QfzVSBNLD2IaPIVPuoAeb4EU7sNpkthoQQw3eABPZdCL1MZu/qCswwI/7SAOZEjVGtXL/C4VpfSCrcZd9Y9FdYTuFfFOCFxcQIg==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: craigkotstest-registry
      namespace: cbodonnell
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: kotsadm-replicated-registry
  namespace: cbodonnell
spec:
  encryptedData:
    .dockerconfigjson: AIAGnAZgM4PKi2jQhC+mSflthQ7R/1XjpJviFDFN+tz3+SEngPSfGhZRMF47hHVrJWb616wxxJs8LQjpcOJvcFKW4qO+aAY+lDSthr4lKxQ+CcRRe+I1aOfaH+hLw7uVH95nEqngVMR7B07KlYUAYbdPPq6w2JOc7myM5h2tJDsvgUGvieyvGs4R1DAleRBZBL8iPPBYQD3pxRrwcbNOyKL+gymngqjGwv27eE+2JbiIGmM9olqGpbb+MUqIv2UqD80hJM6g/QKum8VxzDRA2gDoMuXzfpEr+3WNu+/ZvuCGN6omaUMyhrABhQBVg579v4ZjwP+hxK/q3N2HhQHr9RZyiEc1BtPEz0IeG6EJz3GJmN1MDOcCfLq7Wc9fmRv9F+mbcaC1HD/UdhP76Vq4UG18xwEsDt29QM+pNawfxsgM2lF6+f4WNydWTgQ0MXwSuzRGcdQDN0bOgxExqteVXOnC1x3SElPuOAjWaFzxOTrjveodJjfz78JtCebqtw==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: kotsadm-replicated-registry
      namespace: cbodonnell
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: mysecret
  namespace: cbodonnell
spec:
  encryptedData:
    PASSWORD: AIBs/BU77j/XUGVBHLpOcksoOjdErZ1MT8dU7nsB1GeGmlLnGlpmXd8wzelTqcqihYpUTs+e8/PQ5kdKWg7bq/LMtTmfTXmYSG6Mi1ze3fPGOY43gCrAQQI+DcHih12Q54mTEUOFWTn3piS9WXTyaksscDKIv96cXkfq1BpTXW+SnOZfKpsgkQw/MaqPOW07YKQgWBl4Wj/eE6SK3u0=
    USER_NAME: AICcj6KW6ZXNuUvCVukFJMDiKwJt6f/3MODnW+DT9Cpj4MiLsqrVcjSD5ncex+O5ej0gJ/Irwg4V6EAbOnG1DLf4aT1kTft9zy02ahA9aEv17MI2rPGuirSZb9J7QyIONOdQdhDnUCUKh7m7q0WPTa6te8hUgudv1UpXKO04g1se6hLMfWKnP1UF0J6IpgprWRTMQ5hyOg==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: cbodonnell
    type: Opaque
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: example-nginx
            port:
              number: 80
        path: /
        pathType: Prefix
