apiVersion: v1
data:
  ENV_VAR_1: fake
  ENV_VAR_2: faker
kind: ConfigMap
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-config
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    app: example
    component: nginx
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx
spec:
  ports:
  - port: 80
  selector:
    app: example
    component: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    app: example
    component: nginx
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx
spec:
  selector:
    matchLabels:
      app: example
      component: nginx
  template:
    metadata:
      annotations:
        kots.io/app-slug: craigkotstest
      labels:
        app: example
        component: nginx
        kots.io/app-slug: craigkotstest
        kots.io/backup: velero
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: example-config
        image: nginx
        name: nginx
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 32Mi
      imagePullSecrets:
      - name: craigkotstest-registry
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: craigkotstest-registry
  namespace: cbodonnell
spec:
  encryptedData:
    .dockerconfigjson: AIBdV5s6qGVAv/2m6JEHD8M+dOwcTGvAraCqYkjAzktUtF1TDdE2mGix1SAz0/gLYYGYOrL+/z1HK+SoWFcFKXCQnjeDDQ/6GIt7TG+ZQY4CORb8jUGf2MGEGWN/3mChix3pPYAuZRqrLPjR93AvPxenCKYcsSeZskd2UCoDiBq576Mb3TxOLLrkwQDmDGNS+M3f0veVpw4ju0okHMwQ4fqWhK9M5vhNsTmucscuPXJkG4NU/hyo/VQY1O7Fi+0mYjvFlInl3o7aE7diKR/r3W1zUha2FeDEysnmDOH+ic2XlD0fC4b+W+Lew4/ISHTkidP4STYdejW//cNTelivwSIgjTIxnfdNeQiGDM/u2x3Nvw67VvHlzyTDd1evS9jaY33aTxKoOhd7xbtO2OMadlKtZ+zA7FkBK42iKknI+NBdPVKRHt+i9xGY401Xz0Hd1Wb0vs04bLkUbFALojlH7qTesYgRW1GhGCCvZHjKdFAklMJNHC3HWvHXEgykaQ==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: craigkotstest-registry
      namespace: cbodonnell
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: kotsadm-replicated-registry
  namespace: cbodonnell
spec:
  encryptedData:
    .dockerconfigjson: AIBgDkUMsRE5WIdaJr90Spbxr+qOtJ/+5fVKLPbzOLCYR5t2mNHtgT/BtYBLH9pnO5Nqg29Xe3tgIw7YtIoXtUAQZV5oNTUGkeH9GaTen7R4usO+dAVIMrFQm76TCoebhn0AM/3InUIHqKTR0pdYhqhyCuqdp76bpBiKZvzz2dudK3vvJhlS1DAta6d39/C1J7CVfp+oIwwpYl5JIWtnF7Yrm0+QMbIJ845tClj5jZxVwrgP5UdsQN9TXT06GB3BRANsb5xMqTTvXbGbA9HJ2obpuoXoB2xabC/LG/25Hn7srQ+ORZSXy23aeeKn1vQEkA3jJOL1zdVs3iiFb4W9vgzotwLgxrQKBdMiormaS6AWNJ4J7JjlraZSFAiGz/sSoSgZL2QH2jVtsNdmSqwMJ/gpVLhP9dNpMRcPvu1BPgejlrwH8MeTkkaryHRywGE7I8NfAR+6GSlFIEGDcQlGAYRcJAMK0+/2D8/DR1SP48cfW1PLTKcz2Wuf8n5X9Q==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: kotsadm-replicated-registry
      namespace: cbodonnell
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: mysecret
  namespace: cbodonnell
spec:
  encryptedData:
    PASSWORD: AIBJkZQbUNB6sK1OxCIsO2ypBpS9OvMNyVaUU0F3W7aH8Lw2hHz2Q08WNro9JvKqiGneavtuhOSsRm+okAzE1X0od7Ld3E0OooOTGBnPdxE5dh+xORPQcGjOXOaVnqFum6Dngu+k8c47K8Zi+yGs6Adwsn6sXxxSJANbY5TiFyqRTlNgEZG+S1IT4hs88bu0JTh1ax8b2ZFkI0qQgyk=
    USER_NAME: AIBv2XkUxEVTL8nhHQ5Gi43MmOEkxo0y1/eI52tPeVpsohySter5xRyow+eXAV1MHUTnO/Qlvh7S7x6xlA6sdu3rlyNsDv7LKb7M9TXHOk0lWHYnSvYkx6H1BXPiIRMVdZfLM0LOKqJ/3nCkS3fHBstim9WCvgv7zfNszs3j+RiHDhz8WldC8AbKpbMLxDRQUHOR5hChqA==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: cbodonnell
    type: Opaque
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: example-nginx
            port:
              number: 80
        path: /
        pathType: Prefix
