apiVersion: v1
data:
  ENV_VAR_1: fake
  ENV_VAR_2: more-faker
kind: ConfigMap
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-config
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    app: example
    component: nginx
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx
spec:
  ports:
  - port: 80
  selector:
    app: example
    component: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    app: example
    component: nginx
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx
spec:
  selector:
    matchLabels:
      app: example
      component: nginx
  template:
    metadata:
      annotations:
        kots.io/app-slug: craigkotstest
      labels:
        app: example
        component: nginx
        kots.io/app-slug: craigkotstest
        kots.io/backup: velero
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: example-config
        image: nginx:1.21
        name: nginx
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 32Mi
      imagePullSecrets:
      - name: craigkotstest-registry
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: craigkotstest-registry
  namespace: cbodonnell
spec:
  encryptedData:
    .dockerconfigjson: AIBUzACHFws9Xcxxj6E5SIP0BALMTqbqB4FgmQ7rFB25A+vJBq6jWgx8mCbuZgZ6IxeoQo6liDMi3+qKBKvTaBr2ShEB99deGrVJxoOwQ0rcV7itCZ3Ut/iQl9rQY08USxqn3sEdz298LgG9iMimYq7ZhzneFCw/pfMOsONjEu0c+SndLUX9Uv5TnQx2xxngRmkCx5YC6UQ7EFnC33iwz4nokWVDwSffssMsDQsLZvgCHgT0qQclNqI306un1HmjSVI6t8xdwTDE+sYC8mH4Ii5h21gPhUVp/rcngX3V13UKoMzWFUjWXkfSfete4tp/VsMCNasHy2eypJKjPvUS/cGiPEr+9WBrBE+UAOW02h4N/eoPOR0ZDg32X3URg3Gdw2/7BMzd2WovMgteWC8REKpAmDCnm1IMrSaDitF00/jEgR0sFeWIE0PnJXiTHHyxDniemhVsRkUrvxGxNVvAHL/KGWiku0qKyt9erkn+shmAvHbUlvP0Cs7a+V1yYw==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: craigkotstest-registry
      namespace: cbodonnell
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: kotsadm-replicated-registry
  namespace: cbodonnell
spec:
  encryptedData:
    .dockerconfigjson: AIAiMhINe/Ykf3Cl8Tb6nVlQOjUeK9uqb4EApF/HXgvvbvNKZPC4eV7IN45sRPrP+O3JJxUThmkfMFLNJNS2z7K6/mP90bjBKCCN9QZHaY6Xo8L2SkhCnFn9EBYSrdUAAUa5nV8k8S18XpZozRSKm5EeLJbbZ4iWh1//R/x9Q9Q9Ga0K+8DXyzAauAE9QvXX3L3l/9HDvBakI2yji+IsMXgk9SJz+rXXiWCjAt5IjwldI14dWq5pwCafQ0OXeoBJ3HF2YHyLJQG7yCPXdIwMN7UJem8jkmychQ7kWwjJF88k4enebqbYKtyYJsrH9OSX3T3/5V0kuJayKaHArR36LIRgaVblCFvMB3UxbzJXhWp9H9d+OQkwkPklFxu6+S1VCtzVNRcaO3jF3TVd7tRHCJZgEwR4MxWdPkFWOIH7H8tl2X18iyhq+Nn3/X7T/f3cgQ235UPd/Bpm0gQR2pVuAuk1+OAAFgaRzZogfkgjKED0QuOHSkhswbpUrILoSQ==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: kotsadm-replicated-registry
      namespace: cbodonnell
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: mysecret
  namespace: cbodonnell
spec:
  encryptedData:
    PASSWORD: AICrLGlYJQEn+VTVi0oaa9Jx5Cc9rxRqFSRvUc8n2NyoLwEUgwSJZFung6DCoHjP6Oo3Vqq4RXkmzuapdWoZp4nWwsqYCFqPUX1oJw8IYZ54Ua7r83MMUruph4Qei7PNCgxT6Om45rujuyZtVlnoCcRVSJx7kFdRQ99ClQx5bhxObxUp3cCRTo0R8lFH3Y1Z/pXYLAn4YGiWsSxEMH0=
    USER_NAME: AIBq9tR6u9LW8aT2buglfKLHXJCJfwOCMKK5KUxwKsT0aMmR2e7791wP3B82idQoo2qrTJJjWctso+89uDtf2lKgerBzlNoZnEEbyfl0dsxuqebvc0SOQjupVorFeh4OOSUKw6J070A1cJwAQUFCOhgzsIOzIILpGytReCGZyQ4lWu4xGuijtSDyMAt1JK7XktiE0+U/8Q==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: cbodonnell
    type: Opaque
---
apiVersion: cluster.kurl.sh/v1beta1
kind: Installer
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: craigkotstest-unstable-0.1.54
spec:
  containerd:
    version: 1.5.11
  contour:
    version: 1.21.0
  ekco:
    version: 0.19.2
  kotsadm:
    applicationSlug: craigkotstest/unstable
    applicationVersionLabel: 0.1.54
    version: 1.71.0
  kubernetes:
    version: 1.23.6
  kurl:
    additionalNoProxyAddresses: []
    installerVersion: v2022.06.01-0
  longhorn:
    version: 1.2.4
  minio:
    version: 2020-01-25T02-50-51Z
  prometheus:
    version: 0.56.2-35.2.0
  registry:
    version: 2.7.1
  weave:
    version: 2.6.5
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: example-nginx
            port:
              number: 80
        path: /
        pathType: Prefix
