apiVersion: v1
data:
  ENV_VAR_1: fake
  ENV_VAR_2: faker
kind: ConfigMap
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-config
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    app: example
    component: nginx
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx
spec:
  ports:
  - port: 80
  selector:
    app: example
    component: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    app: example
    component: nginx
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx
spec:
  selector:
    matchLabels:
      app: example
      component: nginx
  template:
    metadata:
      annotations:
        kots.io/app-slug: craigkotstest
      labels:
        app: example
        component: nginx
        kots.io/app-slug: craigkotstest
        kots.io/backup: velero
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: example-config
        image: nginx
        name: nginx
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 32Mi
      imagePullSecrets:
      - name: craigkotstest-registry
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: craigkotstest-registry
  namespace: cbodonnell
spec:
  encryptedData:
    .dockerconfigjson: AIBPqnGTbg9x2G6JF3sT4gww6ian6glRkOD5lU8PhCn4ycKKRzU3eBBzA/iuEnFm8c1yJRY7RBizb8xvEfDqOcWNXNGACS1S8OVH/HnTEbopB9f9gESKCjO6Zjzglc9c7qGqbCqmh+RsAI+Akj2+ryKUopWFVi74tOlme9a05FH8pdARba27x0p80TWRl6motvY27ZmXUWfU8c/W1P5GOhHspamG8+3qTwE/WlHlTARk0duSA2itmV593MPuWJyhJHR0Wum4NUl7CDYid/K97DeKdk8xuQ81PQy4zfJrGg3O3V98AGffRoEJA344H+Sw5EFy7mVn2dmQuG6DV0hdcFt3zlqPdJoUh6Tn2CFg9uK6RHsYskH0jNktFoi/jVSYXJO2tvvPxpk/wWl2qoQmZG9wNNtSDij01ruVVwJB7nM4ePVEBAg6EapaIojZBxXzUvLMI9/N1OlKHxdZa8pv5FsQg+byOE3vEsFAgPEGEqzZ7GchRzF+/qEBRmeYoQ==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: craigkotstest-registry
      namespace: cbodonnell
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: mysecret
  namespace: cbodonnell
spec:
  encryptedData:
    PASSWORD: AIAivXpwHB2r+ghZ8zIF3ZXJBeH78pbl4XfuDAmg1YkByYo24d5sk14oLPoTvIH7vgnDlh0+ucpPKUSKXM/2IbpQK4WCcAs7ikxrguhREdWJSYMWnMcRBLMpY8aogdUPF7NjTEsbA7t0HQSYM5xbpkkF3xrpZes9rLCEHH1gl0TJf+z1uvKHCwM8qB7AfLBmHS5l/TPAvgdhzuG2yqs=
    USER_NAME: AICrjxHdcb2slQ28BlM6TOBifOQjGSD1ic4aTiJcuxHOwbZcbmfCpQeRvyu3+QAfkgW7egyny0+uGHZDbBnOTA+h2F33NqJHFvRSKJ/SDdFFQ0TkXdQSIWl67z6JqQS0RdgTwiZ0LWuA+/NsqkuWmH3bOEu/fxLjcz2M4Jh6sganlABL42nVW6PiZ6v9Ezg6dFglB22UEQ==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: cbodonnell
    type: Opaque
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: example-nginx
            port:
              number: 80
        path: /
        pathType: Prefix
