apiVersion: v1
data:
  ENV_VAR_1: fake
  ENV_VAR_2: more-faker
kind: ConfigMap
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-config
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    app: example
    component: nginx
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx
spec:
  ports:
  - port: 80
  selector:
    app: example
    component: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    app: example
    component: nginx
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx
spec:
  selector:
    matchLabels:
      app: example
      component: nginx
  template:
    metadata:
      annotations:
        kots.io/app-slug: craigkotstest
      labels:
        app: example
        component: nginx
        kots.io/app-slug: craigkotstest
        kots.io/backup: velero
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: example-config
        image: nginx
        name: nginx
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 32Mi
      imagePullSecrets:
      - name: craigkotstest-registry
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: craigkotstest-registry
  namespace: cbodonnell
spec:
  encryptedData:
    .dockerconfigjson: AICWhsRYBEuYzXLUTJdKXH+yOYTEDQFGUutTWQxHau+NwJy9dV/B648S8YYRaTS/ETazgWEsXElQQKT1vAgZzng/HaRwtLgiboEZEnPLHr4JrXu+C+oI3C7eCS2fJfhbkwPYE1qMMzdiS5JXCiSbcygRKOWULtsEAFRUUAn6/FsjHNyjdV+Su+u10E9Y+ok17px4fq1vlKLmXyV6Nj4Xp0Xb6CaVBvuqTFOM+UyJhf7UmsfGVJy1+KewBHD1fvN2ZVUB2XY8pq8n986APGQij3X2l7Kk/ACKvIZ+8faGEQvuW9APgqM4Dp1R5Vem7mrg+8uCnKdF1n0vIBb1wEV0dQWwZj5XiXMGhvNIfFBWsTx4Q0nrJnN0yHNKv9oq0tucz5vTqN9Hd92oYmvvV+dVc/MyIGi4HpIKim/iWmfYgSTsM0RhgwDETSnec5PLTbnEe2yq581vXdbTuZ+jpKAiaQcYBmCHFyHL0sta8Fgul/AIZf/SbJpUO5MJ6XF1sg==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: craigkotstest-registry
      namespace: cbodonnell
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: kotsadm-replicated-registry
  namespace: cbodonnell
spec:
  encryptedData:
    .dockerconfigjson: AIBTCouY8SKq7AUKCoLWXtY6+sWtsxwey0AiEl4LnQXUM5avOu2LoCSaWfcBsdGuzTg1gvr+KcLDnY/W6LHlCIE+2m6by99YIc8aNf4nMZYUie18UwnECEwJeSVNecC9kZ9XPCoPB2r8jK9QJ5DP373CtViOflJ1eZ4jbswGNjcnywzrxQeOAkGyCqzBhKXq6VD8kOP5bKFD2YKTbfgycbKPGO6ygeNQ4OliICKgwJ83xiUibgS3EqlcpW10Ln5DKpqjnbP9jyonMHc0cy2w+e/I3fiwXiN5FISQVgXOC5NkzNGMHL6HCbFalxQMmgOD67zhDFawl2tWaPcfa9NxPS6WwyeUL8xN1lQ5rB9MkjSnn3CZLk0tvODg5wtvkVkBe628Rvz50Oab6HUsqxjeGiai92DvcGEXnWt0cN8IupY8NBcccCVEYHIkyVbyWhg0Vm9tOYZrxMNPIYk5yJfrOWippKvCMZwMOGm5PreCVoJfbVzPI5YTmycUhVACAw==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: kotsadm-replicated-registry
      namespace: cbodonnell
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: mysecret
  namespace: cbodonnell
spec:
  encryptedData:
    PASSWORD: AIAKb3aiHYd4IQ0S9mESY1OabkyuVdZwYzW6mOq9npf9SNQYRq0G7x4ClhrP1pxcypYD4m+MRpbttrGv1GWbS63XYhgo+fbKQs9YSOda0u8KcPmVPWb9c71BvmYrYB5I8ugL88295eYqL4op5yVLKW/Ym/5uXv4ObxhLSwXmy8ivzdkiFxJWcqVYHF4Rh3Si8vz2YoHjSJCkZFGwOxs=
    USER_NAME: AIAaPCCu99E4DQutEBQ8S0u4FUFAnWqU+1F3MHrCHQMqGZcT7nr9/XNnse5BRtFbDZEVr0KWfGEXRH6qcQN8eTdNC9S70iGCTf03QENxP/jWUHzD1lTZgOSmHc8/meOmjIrGoGCL2M/94QUJSuT4q2/Cqzq++VMqQbg6DhBB1ATVYGxigTANv1ulcBVZWCowQ7QhBIkasA==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: cbodonnell
    type: Opaque
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: example-nginx
            port:
              number: 80
        path: /
        pathType: Prefix
