apiVersion: v1
data:
  ENV_VAR_1: fake
  ENV_VAR_2: more-faker
kind: ConfigMap
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-config
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    app: example
    component: nginx
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx
spec:
  ports:
  - port: 80
  selector:
    app: example
    component: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    app: example
    component: nginx
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx
spec:
  selector:
    matchLabels:
      app: example
      component: nginx
  template:
    metadata:
      annotations:
        kots.io/app-slug: craigkotstest
      labels:
        app: example
        component: nginx
        kots.io/app-slug: craigkotstest
        kots.io/backup: velero
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: example-config
        image: nginx:1.22
        name: nginx
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 32Mi
      imagePullSecrets:
      - name: craigkotstest-registry
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: craigkotstest-registry
  namespace: cbodonnell
spec:
  encryptedData:
    .dockerconfigjson: AICRvxYQNVl2doD0lXiCgQLVvBzMGwSk9R+10FY9Veu5HSK8XFUgBq+u/CZBf5/h4fJ3V3myANxbtwU/EWi2x6M3P9RQ+7SgdZZgCP8eRu4Yti1JqwTzCQuO4TwiBkKGqn6EZ4pKdIFyQDT8oF+kfXMrOPX775zzHN7fh2Y0z/qK3PyuoW269vbKTO1Quuzpt/19lHX+g8U/5dugBitygcA3Bl5f1HwuSJz8YRJ8DqZXPTeCdqSWshXzIF2c/XYB6WjyUx6kpK2aIKCpGid+4iYmTMm96epysdC9nEXZUNlGsXfnrmqrM5xPUb0KYaB+0gE3OzVY3djzD9GI8eW6siqvqePXRvJc3b5i+wg5j4yTSdQ4qA8/rMJ/oWchHejH/XZsWHUc/MuZSD6EMMBXP4eKEL9VAYoBwvna4+iUa/OxDtru29j/QvA6UKzZXLaPXESUADmAKnd57rwoGKliIBqr6C3yumXVaTvs0+JMweVhFFv4WnwKWNm/hW46hA==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: craigkotstest-registry
      namespace: cbodonnell
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: kotsadm-replicated-registry
  namespace: cbodonnell
spec:
  encryptedData:
    .dockerconfigjson: AICIJFOrkC6fnUuN2GDF4Yb88/GksGVuYFzxp52waNKS3l0WcVI5vd0lHopONPIW8JRYTMbuEOK3SeiBCw5R6oFNejmhKs9XSrDDg3rFrb9HfGDeMPYDqalL6B13DNMOqjn/vcb06Xl7mXsNXIgWgCuZanenYHNe/bVKrvPy63BVm1zwqKmT47Om0FVBuv+YTqnp7G8JqWkwhaCuIPMXnMwSvbwJAE8nH4BvOs6oz/pqBrGuYT78HDRfdhyauQq3df4G9nzHg42hQ/ujbumRD+0UJQHZ62ScBX2YSzsHLVI2WS2pCWJNe58ZElyno1oK6W5OpWJbV26NTfyZR+sF1a9WuHOuol2FvSY7NHVN2nU2X2WqyTQ9c8DLY9C+gldvqU4CmqPZc68UkynoxUph+hNbgBIRRU1WsNllH9FN1crIuyddBzA0+WDhNWZ42pfVEGks11audfOOsbgX0TYIbejAcvaZ5s7J52gDStW7Yma8d06vNCuTocY7WGn/HA==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: kotsadm-replicated-registry
      namespace: cbodonnell
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  creationTimestamp: null
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: mysecret
  namespace: cbodonnell
spec:
  encryptedData:
    PASSWORD: AIBYTqBmZXxVp2vO3/PLCT5kD5KkcL8xlTix8yxvESswMOM+d+6P5md/liNT1eaxzQ0AA8Q+HfM0z6/zSLOpp5rYFMjQLdJm8ZGO9Q+m9Hc+QGqdwAdDXMVAsmX4UgwpcI6nbwfFWO/rDZiKGOW+Y5YQ+mdbelzo9PNIfSOeNUhoqB0fr0kmIHiGNU7twWtEfatbYbyPVJ7XTBsVibw=
    USER_NAME: AIABnxOlDCSjwxK2CsEboP4gbv37EzD443KKAZBdhmHNHK11zS5bS9mY2QxWi2eZ1edHmV6Plkl44FSF+479pp+mY7uwYGdYuTITkGn8nVVNnK/s3pX/fLqEbl9uQziwpuNlYOt/Vt1zD4fZYivplrsE3jugpMPJ04BY3oi3RJ5Zp0oU54tPWekTR/LYFVxICSVx4qmJEg==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: cbodonnell
    type: Opaque
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kots.io/app-slug: craigkotstest
  labels:
    kots.io/app-slug: craigkotstest
    kots.io/backup: velero
  name: example-nginx-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: example-nginx
            port:
              number: 80
        path: /
        pathType: Prefix
